#ifndef ALISP_LIMITS_H
#define ALISP_LIMITS_H

#define A_FRAME_COUNT 128
#define A_MAX_ARGS 8
#define A_MAX_FIX_SCALE 8
#define A_MAX_RETS 8
#define A_REG_COUNT 128

#define A_FUNC_PAGE_SIZE 256
#define A_MULTI_PAGE_SIZE 256
#define A_OP_PAGE_SIZE 1024
#define A_PRIM_PAGE_SIZE 256
#define A_VAL_PAGE_SIZE 1024

#endif
